//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CupPlaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.Pools = new HashSet<Pool>();
            this.FinalsLinks = new HashSet<FinalsLink>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public FieldSize FieldSize { get; set; }
        public int MatchDuration { get; set; }
    
        public virtual ICollection<Pool> Pools { get; set; }
        public virtual Tournament Tournament { get; set; }
        public virtual DivisionTournament DivisionTournament { get; set; }
        public virtual ICollection<FinalsLink> FinalsLinks { get; set; }
    }
}
