//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CupPlaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Matches = new HashSet<Match>();
            this.Pool = new HashSet<Pool>();
            this.NextFreeTime = new HashSet<NextFreeTime>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public FieldSize Size { get; set; }
    
        public virtual ICollection<Match> Matches { get; set; }
        public virtual ICollection<Pool> Pool { get; set; }
        public virtual Tournament Tournament { get; set; }
        public virtual ICollection<NextFreeTime> NextFreeTime { get; set; }
    }
}
