//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CupPlaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public Match()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartTime { get; set; }
        public int Duration { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
        public virtual Field Field { get; set; }
        public virtual TournamentStage TournamentStage { get; set; }
    }
}
