//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CupPlaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Matches = new HashSet<Match>();
            this.TimeIntervals = new HashSet<TimeInterval>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsAuto { get; set; }
        public Nullable<int> PoolPlacement { get; set; }
    
        public virtual ICollection<Match> Matches { get; set; }
        public virtual Pool Pool { get; set; }
        public virtual ICollection<TimeInterval> TimeIntervals { get; set; }
        public virtual Pool PrevPool { get; set; }
    }
}
